import { darkColors, lightColors, intents, type ColorScheme } from './colors.js';
import { motion } from './animation.js';
import { radius } from './radius.js';
import { shadow } from './shadow.js';
import { space } from './spacing.js';
import { fontFamily, fontSize, fontWeight, letterSpacing } from './typography.js';

/** Prefix used by every generated custom property. */
export const CSS_PREFIX = 'fn';

const kebab = (s: string) => s.replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const slug = (s: string) => s.replace(/\./g, '-');

/** Returns `var(--fn-…)` for a token path such as `color-paper`. */
export const cssVar = (name: string): string => `var(--${CSS_PREFIX}-${name})`;

/** Flatten a colour scheme into `--fn-color-*` and `--fn-intent-*-*` declarations. */
export function colorDeclarations(scheme: ColorScheme): Array<[string, string]> {
  const out: Array<[string, string]> = [];
  for (const [key, value] of Object.entries(scheme)) {
    if (key === 'intents') continue;
    out.push([`--${CSS_PREFIX}-color-${kebab(key)}`, value as string]);
  }
  for (const intent of intents) {
    const set = scheme.intents[intent];
    for (const [part, value] of Object.entries(set)) {
      out.push([`--${CSS_PREFIX}-intent-${intent}-${part}`, value]);
    }
  }
  return out;
}

/** Mode-independent declarations: spacing, radius, typography, motion, layout measures. */
export function baseDeclarations(): Array<[string, string]> {
  const out: Array<[string, string]> = [];
  for (const [k, v] of Object.entries(space)) {
    out.push([`--${CSS_PREFIX}-space-${slug(k)}`, typeof v === 'number' ? `${v / 16}rem` : String(v)]);
  }
  for (const [k, v] of Object.entries(radius)) out.push([`--${CSS_PREFIX}-radius-${k}`, v]);
  for (const [k, v] of Object.entries(fontFamily)) out.push([`--${CSS_PREFIX}-font-${k}`, v]);
  for (const [k, v] of Object.entries(fontSize)) {
    out.push([`--${CSS_PREFIX}-text-${k}`, v.size]);
    out.push([`--${CSS_PREFIX}-leading-${k}`, v.lineHeight]);
  }
  for (const [k, v] of Object.entries(fontWeight)) out.push([`--${CSS_PREFIX}-weight-${k}`, v]);
  for (const [k, v] of Object.entries(letterSpacing)) out.push([`--${CSS_PREFIX}-tracking-${k}`, v]);
  for (const [k, v] of Object.entries(motion.duration)) out.push([`--${CSS_PREFIX}-duration-${k}`, v]);
  for (const [k, v] of Object.entries(motion.easing)) out.push([`--${CSS_PREFIX}-ease-${k}`, v]);
  return out;
}

/** Elevation declarations for one mode. */
export function shadowDeclarations(mode: 'light' | 'dark'): Array<[string, string]> {
  return Object.entries(shadow[mode]).map(([k, v]) => [`--${CSS_PREFIX}-shadow-${k}`, v]);
}

const block = (selector: string, decls: Array<[string, string]>) =>
  `${selector} {\n${decls.map(([k, v]) => `  ${k}: ${v};`).join('\n')}\n}`;

export interface CssVariableOptions {
  /** Include the OS `prefers-color-scheme: dark` fallback. Default true. */
  systemPreference?: boolean;
}

/**
 * Generates the complete variables stylesheet.
 *
 * Mode resolution (highest specificity wins):
 *  1. `[data-theme="dark"]` / `[data-theme="light"]` on any element.
 *  2. `:root` follows the OS preference when no explicit mode is set.
 */
export function createCssVariables(options: CssVariableOptions = {}): string {
  const systemPreference = options.systemPreference ?? true;
  const light = colorDeclarations(lightColors);
  const dark = colorDeclarations(darkColors);
  const parts = [
    '/* FieldNote UI design tokens. GENERATED by @fieldnote-ui/tokens — do not edit. */',
    block(':root', [...baseDeclarations(), ...shadowDeclarations('light'), ...light]),
    block('[data-theme="light"]', [...shadowDeclarations('light'), ...light]),
    block('[data-theme="dark"]', [...shadowDeclarations('dark'), ...dark]),
  ];
  if (systemPreference) {
    parts.push(
      `@media (prefers-color-scheme: dark) {\n${block(':root:not([data-theme="light"])', [
        ...shadowDeclarations('dark'),
        ...dark,
      ])
        .split('\n')
        .map((l) => (l.startsWith('}') ? l : `  ${l}`))
        .join('\n')}\n}`,
    );
  }
  parts.push(
    '/* Reduced motion: collapse every duration token. */',
    `@media (prefers-reduced-motion: reduce) {\n  :root {\n${motionOverrides()}  }\n}`,
  );
  return `${parts.join('\n\n')}\n`;
}

function motionOverrides(): string {
  return Object.keys(motion.duration)
    .filter((k) => k !== 'instant')
    .map((k) => `    --${CSS_PREFIX}-duration-${k}: 0ms;\n`)
    .join('');
}
